title: Page Title
author: Mervyn Galvin
email: mervyn511@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Site description

# social links
twitter_username: avitus27 # DO NOT include the @ character, or else the build will fail!
github_username:  avitus27 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
